<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\PaymentTransaction;
use App\Models\Transaction;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;

class RazorpayWebhookTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    public function test_webhook_processes_payment_captured_event()
    {
        // Create a test user
        $user = User::factory()->create();

        // Create a test transaction
        $transaction = Transaction::create([
            'user_id' => $user->id,
            'order_number' => 'TEST-ORDER-001',
            'total_amount' => 1000,
            'customer_name' => 'Test Customer',
            'customer_phone' => '1234567890',
            'payment_status' => 'Pending'
        ]);

        // Create a payment transaction
        $paymentTransaction = PaymentTransaction::create([
            'transaction_id' => $transaction->id,
            'user_id' => $user->id,
            'razorpay_order_id' => 'order_test123',
            'razorpay_payment_id' => 'pay_test123',
            'status' => 'pending',
            'amount' => 1000,
            'metadata' => json_encode([
                'items' => [
                    [
                        'product_id' => 1,
                        'name' => 'Test Product',
                        'quantity' => 1,
                        'price' => 1000
                    ]
                ]
            ])
        ]);

        // Mock webhook payload
        $payload = [
            'event' => 'payment.captured',
            'payload' => [
                'payment' => [
                    'entity' => [
                        'id' => 'pay_test123',
                        'status' => 'captured',
                        'amount' => 100000,
                        'currency' => 'INR'
                    ]
                ]
            ]
        ];

        // Mock webhook signature (in real scenario, this would be generated by Razorpay)
        $signature = 'test_signature';

        // Send webhook request
        $response = $this->postJson('/api/razorpay/webhook', $payload, [
            'X-Razorpay-Signature' => $signature
        ]);

        // Assert response
        $response->assertStatus(200);
        $response->assertJson([
            'status' => 'success'
        ]);

        // Refresh models from database
        $paymentTransaction->refresh();
        $transaction->refresh();

        // Assert payment transaction is updated
        $this->assertEquals('completed', $paymentTransaction->status);
        $this->assertEquals('pay_test123', $paymentTransaction->razorpay_payment_id);

        // Assert transaction is updated
        $this->assertEquals('Paid', $transaction->payment_status);
    }

    public function test_webhook_rejects_invalid_signature()
    {
        $payload = [
            'event' => 'payment.captured',
            'payload' => [
                'payment' => [
                    'entity' => [
                        'id' => 'pay_test123'
                    ]
                ]
            ]
        ];

        $response = $this->postJson('/api/razorpay/webhook', $payload, [
            'X-Razorpay-Signature' => 'invalid_signature'
        ]);

        $response->assertStatus(400);
    }

    public function test_webhook_requires_signature_header()
    {
        $payload = [
            'event' => 'payment.captured',
            'payload' => [
                'payment' => [
                    'entity' => [
                        'id' => 'pay_test123'
                    ]
                ]
            ]
        ];

        $response = $this->postJson('/api/razorpay/webhook', $payload);

        $response->assertStatus(400);
        $response->assertJson([
            'message' => 'Signature missing'
        ]);
    }
} 